const INGREDIENTS = [
  {id:'bottom',name:'面包底',emoji:'🍞'}, {id:'beef',name:'牛肉饼',emoji:'🥩'},
  {id:'lettuce',name:'生菜',emoji:'🥬'}, {id:'tomato',name:'西红柿',emoji:'🍅'},
  {id:'cheese',name:'芝士',emoji:'🧀'}, {id:'ketchup',name:'番茄酱',emoji:'🔴'},
  {id:'ham',name:'火腿',emoji:'🥓'}, {id:'onion',name:'洋葱',emoji:'🧅'},
  {id:'mayo',name:'蛋黄酱',emoji:'⚪'}, {id:'top',name:'面包顶',emoji:'🥯'}
];
const LEVELS = [
  {name:'阳光社区 · 第 1 天',goal:5,queue:1,time:38,unlocked:4,recipes:[['bottom','beef','lettuce','top'],['bottom','beef','tomato','top']]},
  {name:'阳光社区 · 第 2 天',goal:6,queue:2,time:34,unlocked:5,recipes:[['bottom','beef','cheese','top'],['bottom','beef','lettuce','tomato','top']]},
  {name:'午餐高峰 · 第 3 天',goal:7,queue:3,time:31,unlocked:6,recipes:[['bottom','beef','cheese','ketchup','top'],['bottom','beef','lettuce','tomato','ketchup','top']]},
  {name:'人气餐车 · 第 4 天',goal:8,queue:3,time:28,unlocked:8,recipes:[['bottom','ham','cheese','lettuce','top'],['bottom','beef','cheese','onion','ketchup','top'],['bottom','beef','beef','cheese','top']]},
  {name:'乔乔挑战 · 第 5 天',goal:10,queue:3,time:25,unlocked:10,recipes:[['bottom','ham','lettuce','tomato','mayo','top'],['bottom','beef','beef','cheese','onion','ketchup','top'],['bottom','beef','lettuce','tomato','onion','mayo','top']]}
];
const ENDLESS_RECIPES=[...LEVELS[4].recipes,['bottom','ham','cheese','onion','mayo','top'],['bottom','beef','cheese','lettuce','tomato','ketchup','top'],['bottom','beef','beef','cheese','lettuce','onion','mayo','top']];
const UPGRADES={seats:{name:'等待座位',icon:'🪑',desc:'排队顾客耐心消耗降低',effect:['无加成','降低 12%','降低 24%','降低 36%'],costs:[250,700,1500]},kitchen:{name:'高效厨房',icon:'🍳',desc:'所有顾客耐心消耗降低',effect:['无加成','降低 6%','降低 12%','降低 18%'],costs:[400,1000,2200]},sign:{name:'人气招牌',icon:'✨',desc:'每笔订单基础收入提高',effect:['无加成','提高 10%','提高 20%','提高 30%'],costs:[500,1200,2600]}};
const PEOPLE=['👩🏻','👨🏽','👧🏻','🧑🏾','👨🏻‍🦱','👩🏼‍🦰','🧔🏻','👵🏻'];
const $=s=>document.querySelector(s);
const SFX={
  ctx:null,muted:localStorage.getItem('qiaojiaoMuted')==='1',
  init(){if(!this.ctx)this.ctx=new(window.AudioContext||window.webkitAudioContext)();if(this.ctx.state==='suspended')this.ctx.resume()},
  startMusic(){const bgm=$('#bgm');bgm.volume=.32;if(!this.muted)bgm.play().catch(()=>{})},
  tone(freq,duration=.08,type='sine',delay=0,volume=.055){if(this.muted)return;this.init();const osc=this.ctx.createOscillator(),gain=this.ctx.createGain(),start=this.ctx.currentTime+delay;osc.type=type;osc.frequency.setValueAtTime(freq,start);gain.gain.setValueAtTime(.001,start);gain.gain.exponentialRampToValueAtTime(volume,start+.01);gain.gain.exponentialRampToValueAtTime(.001,start+duration);osc.connect(gain).connect(this.ctx.destination);osc.start(start);osc.stop(start+duration+.02)},
  play(name){if(this.muted)return;const sounds={tap:[[480,.045,'sine',0,.025]],undo:[[330,.07,'triangle',0,.035]],trash:[[180,.11,'sawtooth',0,.025]],good:[[523,.08,'sine',0,.05],[659,.08,'sine',.07,.05],[784,.13,'sine',.14,.055]],bad:[[220,.13,'sawtooth',0,.035],[165,.18,'sawtooth',.1,.03]],combo:[[659,.06,'square',0,.035],[784,.06,'square',.06,.035],[988,.12,'square',.12,.04]],finish:[[523,.1,'sine',0,.05],[659,.1,'sine',.1,.05],[784,.1,'sine',.2,.05],[1047,.24,'sine',.3,.055]]};(sounds[name]||[]).forEach(x=>this.tone(...x))},
  toggle(){this.muted=!this.muted;localStorage.setItem('qiaojiaoMuted',this.muted?'1':'0');updateSoundButton();const bgm=$('#bgm');if(this.muted){bgm.pause()}else{this.init();this.startMusic();this.play('tap')}}
};
let state={level:0,coins:0,score:0,combo:0,served:0,attempts:0,correct:0,earned:0,customers:[],stack:[],upgrades:{seats:0,kitchen:0,sign:0},running:false,completed:false,lastTick:0,lastSaveAt:0};
let nextCustomerId=1,timerFrame,toastTimer;

function level(){if(state.level<LEVELS.length)return LEVELS[state.level];const extra=state.level-LEVELS.length+1;return{name:`无限营业 · 第 ${state.level+1} 天`,goal:Math.min(20,10+Math.ceil(extra/2)),queue:Math.min(5,3+Math.floor(extra/3)),time:Math.max(17,25-extra),unlocked:10,recipes:ENDLESS_RECIPES}}
function saveProgress(){const data={level:state.level,coins:state.coins,score:state.score,combo:state.combo,served:state.served,attempts:state.attempts,correct:state.correct,earned:state.earned,customers:state.customers,stack:state.stack,upgrades:state.upgrades,running:state.running,completed:state.completed};localStorage.setItem('qiaojiaoProgressV2',JSON.stringify(data));localStorage.setItem('qiaojoCoins',state.coins)}
function loadProgress(){try{const data=JSON.parse(localStorage.getItem('qiaojiaoProgressV2'));if(!data)return false;Object.assign(state,data);state.upgrades={seats:0,kitchen:0,sign:0,...data.upgrades};state.customers=(state.customers||[]).map(c=>({...c,price:c.price||recipePrice(c.recipe),gifted:Boolean(c.gifted)}));if(state.completed){state.level++;state.served=0;state.attempts=0;state.correct=0;state.earned=0;state.combo=0;state.stack=[];state.customers=[];state.running=false;state.completed=false;saveProgress()}nextCustomerId=Math.max(1,...state.customers.map(c=>c.id+1));return state.running&&state.customers.length>0}catch{return false}}
function ing(id){return INGREDIENTS.find(x=>x.id===id)}
function recipeForCustomer(){const list=level().recipes;return [...list[Math.floor(Math.random()*list.length)]]}
function recipePrice(recipe){return 12+recipe.length*7}
function createCustomer(){const recipe=recipeForCustomer();return{id:nextCustomerId++,face:PEOPLE[Math.floor(Math.random()*PEOPLE.length)],recipe,price:recipePrice(recipe),gifted:false,patience:100,maxTime:level().time}}
function fillQueue(){while(state.customers.length<level().queue)state.customers.push(createCustomer());renderCustomers();renderOrder();saveProgress()}
function renderIngredients(){const unlocked=INGREDIENTS.filter((_,i)=>i<level().unlocked||i===9);$('#ingredients').innerHTML=unlocked.map(x=>`<button class="ingredient" data-id="${x.id}"><span>${x.emoji}</span>${x.name}</button>`).join('');$('#unlockHint').textContent=`已解锁 ${unlocked.length} 种`;document.querySelectorAll('.ingredient').forEach(b=>b.onclick=()=>addIngredient(b.dataset.id))}
function renderCustomers(){$('#customerQueue').innerHTML=state.customers.map((c,i)=>`<div class="customer ${i===0?'active':''}" data-customer-id="${c.id}"><div class="bubble"><div class="mini-order">${c.recipe.map(id=>`<span>${ing(id).emoji}</span>`).join('')}</div></div><div class="person">${c.face}</div><div class="patience"><i style="width:${c.patience}%;background:${c.patience<30?'#ef544b':c.patience<60?'#f0a93d':'#64b86b'}"></i></div><button class="gift-btn" type="button" ${c.patience<65&&!c.gifted?'':'hidden'}>🎁 ${Math.ceil(c.price/2)}</button></div>`).join('');document.querySelectorAll('.gift-btn').forEach(btn=>btn.onclick=()=>giftCustomer(Number(btn.closest('.customer').dataset.customerId)))}
function updatePatienceBars(){document.querySelectorAll('.customer').forEach((el,i)=>{const c=state.customers[i],value=Math.max(0,c?.patience??0),bar=el.querySelector('.patience i'),gift=el.querySelector('.gift-btn');bar.style.width=`${value}%`;bar.style.background=value<30?'#ef544b':value<60?'#f0a93d':'#64b86b';gift.hidden=!(value<65&&!c.gifted)})}
function renderOrder(){const c=state.customers[0];if(!c){$('#orderTicket').className='order-ticket empty';$('#orderTicket').textContent='下一位顾客马上就到…';return}$('#orderTimer').textContent=`耐心 ${Math.ceil(c.patience)}%`;$('#orderTicket').className='order-ticket';$('#orderTicket').innerHTML=`<div class="ticket-head"><b>订单 #${String(c.id).padStart(3,'0')}</b><span class="price-tag">🪙 ${c.price}</span></div>${c.recipe.map((id,i)=>`<div class="recipe-row ${state.stack[i]===id?'done':''}"><span class="emoji">${ing(id).emoji}</span><span>${i+1}. ${ing(id).name}</span></div>`).join('')}${state.level>=2?'<div class="special-note">💡 注意配料数量和顺序</div>':''}`}
function renderStack(){const el=$('#burgerStack');el.innerHTML=state.stack.length?state.stack.map(id=>`<div class="stack-item" title="${ing(id).name}">${ing(id).emoji}</div>`).join(''):'<span class="plate-hint">点击下方食材开始制作</span>';renderOrder()}
function renderStats(){const l=level();$('#coins').textContent=state.coins;$('#score').textContent=state.score;$('#combo').textContent=state.combo;$('.combo-stat').classList.toggle('hot',state.combo>=3);$('#levelName').textContent=l.name;$('#target').textContent=`完成 ${l.goal} 单`;$('#progressText').textContent=`${state.served} / ${l.goal} 单`;$('#levelProgress').style.width=`${Math.min(100,state.served/l.goal*100)}%`}
function addIngredient(id){if(!state.running||!state.customers.length)return;if(state.stack.length>=8){toast('汉堡已经太高啦！','bad');SFX.play('bad');return}SFX.play('tap');state.stack.push(id);renderStack();saveProgress()}
function arraysEqual(a,b){return a.length===b.length&&a.every((v,i)=>v===b[i])}
function giftCustomer(id){const c=state.customers.find(x=>x.id===id);if(!c||c.gifted||c.patience>=65)return;const cost=Math.ceil(c.price/2);if(state.coins<cost){SFX.play('bad');toast(`金币不足，需要 ${cost} 金币`,'bad');return}state.coins-=cost;c.patience=100;c.gifted=true;SFX.play('good');toast(`送出小礼物，顾客耐心已恢复！-${cost} 金币`,'good');renderCustomers();renderOrder();renderStats();saveProgress()}
function serve(){if(!state.running||!state.customers.length)return;if(!state.stack.length){toast('还没有制作汉堡哦','bad');SFX.play('bad');return}const c=state.customers[0];state.attempts++;if(arraysEqual(state.stack,c.recipe)){state.correct++;state.served++;state.combo++;SFX.play(state.combo>=3?'combo':'good');const speed=Math.round(c.patience/10),base=Math.round(c.price*(1+state.upgrades.sign*.1)),gain=base+speed+Math.min(state.combo,10)*2;state.coins+=gain;state.earned+=gain;state.score+=100+c.recipe.length*20+speed*5+state.combo*10;toast(state.combo>=3?`🔥 ${state.combo} 连击！+${gain} 金币`:`完美交付！+${gain} 金币`,'good');$('.build-panel').classList.add('success-flash');setTimeout(()=>$('.build-panel').classList.remove('success-flash'),500);state.customers.shift();state.stack=[];renderStack();renderStats();if(state.served>=level().goal){finishLevel();return}fillQueue()}else{SFX.play('bad');state.combo=0;state.score=Math.max(0,state.score-30);toast('配方不对，再检查一下！','bad');$('.build-panel').classList.add('shake');setTimeout(()=>$('.build-panel').classList.remove('shake'),400);renderStats()}}
function customerLeaves(){SFX.play('bad');state.combo=0;state.attempts++;state.customers.shift();toast('顾客等太久离开了，汉堡保留给下一位顾客','bad');renderStats();fillQueue()}
function tick(t){if(!state.running)return;if(!state.lastTick)state.lastTick=t;const dt=(t-state.lastTick)/1000;state.lastTick=t;state.customers.forEach((c,i)=>{const kitchenFactor=1-state.upgrades.kitchen*.06,seatFactor=i>0?1-state.upgrades.seats*.12:1;c.patience-=dt/c.maxTime*100*(1+i*.12)*kitchenFactor*seatFactor});if(state.customers[0]?.patience<=0)customerLeaves();updatePatienceBars();if(state.customers[0])$('#orderTimer').textContent=`耐心 ${Math.max(0,Math.ceil(state.customers[0].patience))}%`;if(t-state.lastSaveAt>1000){state.lastSaveAt=t;saveProgress()}timerFrame=requestAnimationFrame(tick)}
function toast(msg,type=''){const el=$('#toast');clearTimeout(toastTimer);el.textContent=msg;el.className=`toast show ${type}`;toastTimer=setTimeout(()=>el.className='toast',1600)}
function startLevel(resume=false){if(!resume){const legacyCoins=Number(localStorage.getItem('qiaojoCoins')||0);if(state.coins===0)state.coins=legacyCoins;state.served=0;state.attempts=0;state.correct=0;state.earned=0;state.combo=0;state.stack=[];state.customers=[]}state.running=true;state.completed=false;state.lastTick=0;state.lastSaveAt=0;$('#startModal').classList.remove('show');$('#resultModal').classList.remove('show');renderIngredients();renderStack();renderStats();fillQueue();saveProgress();cancelAnimationFrame(timerFrame);timerFrame=requestAnimationFrame(tick)}
function finishLevel(){state.running=false;state.completed=true;cancelAnimationFrame(timerFrame);SFX.play('finish');saveProgress();const accuracy=state.attempts?state.correct/state.attempts:1;const stars=accuracy>=.9?3:accuracy>=.7?2:1;$('#resultStars').textContent='⭐'.repeat(stars)+'☆'.repeat(3-stars);$('#resultTitle').textContent=stars===3?'太棒了，乔乔！':stars===2?'今天也很不错！':'再接再厉，乔乔！';$('#resultOrders').textContent=state.served;$('#resultCoins').textContent=state.earned;$('#resultAccuracy').textContent=`${Math.round(accuracy*100)}%`;$('#newUnlock').textContent=state.level===LEVELS.length-1?'🏆 明天开启无限营业模式，难度会继续提升！':'🎁 新一天的顾客数量与订单难度将继续提升！';$('#nextBtn').textContent='进入下一天';setTimeout(()=>$('#resultModal').classList.add('show'),500)}
let shopPaused=false;
function renderUpgradeShop(){$('#shopCoins').textContent=state.coins;$('#upgradeList').innerHTML=Object.entries(UPGRADES).map(([id,u])=>{const lv=state.upgrades[id],max=lv>=u.costs.length,cost=u.costs[lv];return`<div class="upgrade-item"><div class="upgrade-icon">${u.icon}</div><div class="upgrade-copy"><b>${u.name} · ${lv}级</b><span>${u.desc}</span><small>${u.effect[lv]}</small></div><button class="upgrade-buy" data-upgrade="${id}" ${max||state.coins<cost?'disabled':''}>${max?'已满级':`升级 🪙${cost}`}</button></div>`}).join('');document.querySelectorAll('.upgrade-buy').forEach(btn=>btn.onclick=()=>buyUpgrade(btn.dataset.upgrade))}
function buyUpgrade(id){const u=UPGRADES[id],lv=state.upgrades[id];if(!u||lv>=u.costs.length)return;const cost=u.costs[lv];if(state.coins<cost){toast('金币不足，继续营业赚钱吧','bad');return}state.coins-=cost;state.upgrades[id]++;SFX.play('finish');renderStats();renderUpgradeShop();saveProgress();toast(`${u.name} 已升级到 ${state.upgrades[id]} 级`,'good')}
function openUpgradeShop(){shopPaused=state.running;if(shopPaused)cancelAnimationFrame(timerFrame);renderUpgradeShop();$('#upgradeModal').classList.add('show')}
function closeUpgradeShop(){$('#upgradeModal').classList.remove('show');if(shopPaused&&state.running){state.lastTick=0;timerFrame=requestAnimationFrame(tick)}shopPaused=false}
function updateSoundButton(){const btn=$('#soundBtn');btn.classList.toggle('muted',SFX.muted);btn.querySelector('span').textContent=SFX.muted?'🔇':'🔊';btn.querySelector('b').textContent=SFX.muted?'静音':'音效';btn.querySelector('small').textContent=SFX.muted?'关闭':'开启';btn.setAttribute('aria-label',SFX.muted?'开启音效':'关闭音效')}
const hasSavedGame=loadProgress();if(hasSavedGame)$('#startBtn').textContent='继续营业';$('#startBtn').onclick=()=>{SFX.init();SFX.startMusic();SFX.play('good');startLevel(hasSavedGame&&state.running)};$('#soundBtn').onclick=()=>SFX.toggle();$('#upgradeBtn').onclick=openUpgradeShop;$('#closeUpgradeBtn').onclick=closeUpgradeShop;$('#upgradeModal').onclick=e=>{if(e.target===$('#upgradeModal'))closeUpgradeShop()};$('#serveBtn').onclick=serve;$('#undoBtn').onclick=()=>{if(state.stack.pop()){SFX.play('undo');renderStack();saveProgress()}};$('#trashBtn').onclick=()=>{if(state.stack.length){SFX.play('trash');state.stack=[];state.combo=0;renderStack();renderStats();saveProgress();toast('已清空制作台')}};$('#nextBtn').onclick=()=>{state.level++;state.completed=false;startLevel(false)};window.addEventListener('pagehide',saveProgress);updateSoundButton();renderStats();renderIngredients();
