const INGREDIENTS = [
  {id:'bottom',name:'面包底',emoji:'🍞'}, {id:'beef',name:'牛肉饼',emoji:'🥩'},
  {id:'lettuce',name:'生菜',emoji:'🥬'}, {id:'tomato',name:'西红柿',emoji:'🍅'},
  {id:'cheese',name:'芝士',emoji:'🧀'}, {id:'ketchup',name:'番茄酱',emoji:'🔴'},
  {id:'ham',name:'火腿',emoji:'🥓'}, {id:'onion',name:'洋葱',emoji:'🧅'},
  {id:'mayo',name:'蛋黄酱',emoji:'⚪'}, {id:'top',name:'面包顶',emoji:'🥯'}
];
const LEVELS = [
  {name:'阳光社区 · 第 1 天',goal:5,queue:1,time:38,unlocked:4,recipes:[['bottom','beef','lettuce','top'],['bottom','beef','tomato','top']]},
  {name:'阳光社区 · 第 2 天',goal:6,queue:2,time:34,unlocked:5,recipes:[['bottom','beef','cheese','top'],['bottom','beef','lettuce','tomato','top']]},
  {name:'午餐高峰 · 第 3 天',goal:7,queue:3,time:31,unlocked:6,recipes:[['bottom','beef','cheese','ketchup','top'],['bottom','beef','lettuce','tomato','ketchup','top']]},
  {name:'人气餐车 · 第 4 天',goal:8,queue:3,time:28,unlocked:8,recipes:[['bottom','ham','cheese','lettuce','top'],['bottom','beef','cheese','onion','ketchup','top'],['bottom','beef','beef','cheese','top']]},
  {name:'乔乔挑战 · 第 5 天',goal:10,queue:3,time:25,unlocked:10,recipes:[['bottom','ham','lettuce','tomato','mayo','top'],['bottom','beef','beef','cheese','onion','ketchup','top'],['bottom','beef','lettuce','tomato','onion','mayo','top']]}
];
const PEOPLE=['👩🏻','👨🏽','👧🏻','🧑🏾','👨🏻‍🦱','👩🏼‍🦰','🧔🏻','👵🏻'];
const $=s=>document.querySelector(s);
let state={level:0,coins:0,score:0,combo:0,served:0,attempts:0,correct:0,earned:0,customers:[],stack:[],running:false,lastTick:0};
let nextCustomerId=1,timerFrame,toastTimer;

function level(){return LEVELS[Math.min(state.level,LEVELS.length-1)]}
function ing(id){return INGREDIENTS.find(x=>x.id===id)}
function recipeForCustomer(){const list=level().recipes;return [...list[Math.floor(Math.random()*list.length)]]}
function createCustomer(){return{id:nextCustomerId++,face:PEOPLE[Math.floor(Math.random()*PEOPLE.length)],recipe:recipeForCustomer(),patience:100,maxTime:level().time}}
function fillQueue(){while(state.customers.length<level().queue)state.customers.push(createCustomer());renderCustomers();renderOrder()}
function renderIngredients(){const unlocked=INGREDIENTS.filter((_,i)=>i<level().unlocked||i===9);$('#ingredients').innerHTML=unlocked.map(x=>`<button class="ingredient" data-id="${x.id}"><span>${x.emoji}</span>${x.name}</button>`).join('');$('#unlockHint').textContent=`已解锁 ${unlocked.length} 种`;document.querySelectorAll('.ingredient').forEach(b=>b.onclick=()=>addIngredient(b.dataset.id))}
function renderCustomers(){ $('#customerQueue').innerHTML=state.customers.map((c,i)=>`<div class="customer ${i===0?'active':''}"><div class="bubble"><div class="mini-order">${c.recipe.map(id=>`<span>${ing(id).emoji}</span>`).join('')}</div></div><div class="person">${c.face}</div><div class="patience"><i style="width:${c.patience}%;background:${c.patience<30?'#ef544b':c.patience<60?'#f0a93d':'#64b86b'}"></i></div></div>`).join('') }
function updatePatienceBars(){document.querySelectorAll('.patience i').forEach((bar,i)=>{const value=Math.max(0,state.customers[i]?.patience??0);bar.style.width=`${value}%`;bar.style.background=value<30?'#ef544b':value<60?'#f0a93d':'#64b86b'})}
function renderOrder(){const c=state.customers[0];if(!c){$('#orderTicket').className='order-ticket empty';$('#orderTicket').textContent='下一位顾客马上就到…';return}$('#orderTimer').textContent=`耐心 ${Math.ceil(c.patience)}%`;$('#orderTicket').className='order-ticket';$('#orderTicket').innerHTML=`<div class="ticket-head"><b>订单 #${String(c.id).padStart(3,'0')}</b><span>${c.recipe.length>=6?'⭐ 复杂订单':'今日现做'}</span></div>${c.recipe.map((id,i)=>`<div class="recipe-row ${state.stack[i]===id?'done':''}"><span class="emoji">${ing(id).emoji}</span><span>${i+1}. ${ing(id).name}</span></div>`).join('')}${state.level>=2?'<div class="special-note">💡 注意配料数量和顺序</div>':''}`}
function renderStack(){const el=$('#burgerStack');el.innerHTML=state.stack.length?state.stack.map(id=>`<div class="stack-item" title="${ing(id).name}">${ing(id).emoji}</div>`).join(''):'<span class="plate-hint">点击下方食材开始制作</span>';renderOrder()}
function renderStats(){const l=level();$('#coins').textContent=state.coins;$('#score').textContent=state.score;$('#combo').textContent=state.combo;$('.combo-stat').classList.toggle('hot',state.combo>=3);$('#levelName').textContent=l.name;$('#target').textContent=`完成 ${l.goal} 单`;$('#progressText').textContent=`${state.served} / ${l.goal} 单`;$('#levelProgress').style.width=`${Math.min(100,state.served/l.goal*100)}%`}
function addIngredient(id){if(!state.running||!state.customers.length)return;if(state.stack.length>=8){toast('汉堡已经太高啦！','bad');return}state.stack.push(id);renderStack()}
function arraysEqual(a,b){return a.length===b.length&&a.every((v,i)=>v===b[i])}
function serve(){if(!state.running||!state.customers.length)return;if(!state.stack.length){toast('还没有制作汉堡哦','bad');return}const c=state.customers[0];state.attempts++;if(arraysEqual(state.stack,c.recipe)){state.correct++;state.served++;state.combo++;const speed=Math.round(c.patience/10);const gain=15+c.recipe.length*3+speed+Math.min(state.combo,10)*2;state.coins+=gain;state.earned+=gain;state.score+=100+c.recipe.length*20+speed*5+state.combo*10;toast(state.combo>=3?`🔥 ${state.combo} 连击！+${gain} 金币`:`完美交付！+${gain} 金币`,'good');$('.build-panel').classList.add('success-flash');setTimeout(()=>$('.build-panel').classList.remove('success-flash'),500);state.customers.shift();state.stack=[];renderStack();renderStats();if(state.served>=level().goal){finishLevel();return}fillQueue()}else{state.combo=0;state.score=Math.max(0,state.score-30);toast('配方不对，再检查一下！','bad');$('.build-panel').classList.add('shake');setTimeout(()=>$('.build-panel').classList.remove('shake'),400);renderStats()}}
function customerLeaves(){state.combo=0;state.attempts++;state.customers.shift();state.stack=[];toast('顾客等太久离开了…','bad');renderStack();renderStats();fillQueue()}
function tick(t){if(!state.running)return;if(!state.lastTick)state.lastTick=t;const dt=(t-state.lastTick)/1000;state.lastTick=t;state.customers.forEach((c,i)=>c.patience-=dt/c.maxTime*100*(1+i*.12));if(state.customers[0]?.patience<=0)customerLeaves();updatePatienceBars();if(state.customers[0])$('#orderTimer').textContent=`耐心 ${Math.max(0,Math.ceil(state.customers[0].patience))}%`;timerFrame=requestAnimationFrame(tick)}
function toast(msg,type=''){const el=$('#toast');clearTimeout(toastTimer);el.textContent=msg;el.className=`toast show ${type}`;toastTimer=setTimeout(()=>el.className='toast',1600)}
function startLevel(){const saved=Number(localStorage.getItem('qiaojoCoins')||0);if(state.level===0&&state.coins===0)state.coins=saved;state.served=0;state.attempts=0;state.correct=0;state.earned=0;state.combo=0;state.stack=[];state.customers=[];state.running=true;state.lastTick=0;$('#startModal').classList.remove('show');$('#resultModal').classList.remove('show');renderIngredients();renderStack();renderStats();fillQueue();cancelAnimationFrame(timerFrame);timerFrame=requestAnimationFrame(tick)}
function finishLevel(){state.running=false;cancelAnimationFrame(timerFrame);localStorage.setItem('qiaojoCoins',state.coins);const accuracy=state.attempts?state.correct/state.attempts:1;const stars=accuracy>=.9?3:accuracy>=.7?2:1;$('#resultStars').textContent='⭐'.repeat(stars)+'☆'.repeat(3-stars);$('#resultTitle').textContent=stars===3?'太棒了，乔乔！':stars===2?'今天也很不错！':'再接再厉，乔乔！';$('#resultOrders').textContent=state.served;$('#resultCoins').textContent=state.earned;$('#resultAccuracy').textContent=`${Math.round(accuracy*100)}%`;const next=LEVELS[state.level+1];$('#newUnlock').textContent=next?`🎁 新一天将解锁更多食材，顾客也会更多！`:'🏆 已完成全部营业日，接下来进入无限挑战！';$('#nextBtn').textContent=next?'进入下一天':'再次挑战';setTimeout(()=>$('#resultModal').classList.add('show'),500)}
$('#startBtn').onclick=startLevel;$('#serveBtn').onclick=serve;$('#undoBtn').onclick=()=>{if(state.stack.pop())renderStack()};$('#trashBtn').onclick=()=>{if(state.stack.length){state.stack=[];state.combo=0;renderStack();renderStats();toast('已清空制作台')}};$('#nextBtn').onclick=()=>{if(state.level<LEVELS.length-1)state.level++;startLevel()};renderStats();renderIngredients();
